version: "3.6"

services:

  deployment:
    build: .
    environment:
    - MARKETPLACE_HOST
    - CALLBACK_URL
    secrets:
      - client_id
      - client_secret
      - scopes
      - flask_secret
    ports:
      - 5000:5000

secrets:
  client_id:
    file: ./secrets/client_id
  client_secret:
    file: ./secrets/client_secret
  scopes:
    file: ./secrets/scopes
  flask_secret:
    file: ./secrets/flask_secret
